services:
  - type: web
    name: nlsbox-backend
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_STRING
        sync: false
